### ISSUE TITLE
Location data not longer available

### ISSUE THREAD

**Issue by sehroriginell** [GroupePSA/groupepsa.github.io#72]
When polling for the car's position I got valid locations up until about two weeks ago. Since end of March / start of April the response looks like this:

```
{
   "uuid": "...",
   "code": 40400,
   "message": "Not Found: Position not found."
}
```

I suspect the car to be the problem. It did not provide new status data until I made a full reset (disconnecting the car's battery for a few minutes). After that I was able to retrieve up to date status data. Still, the lastPosition reply looks like above.

Any idea on how I can get this back to work?

**Comment by sehroriginell** [comment]
Any news on this? Maybe you can help, @etiennerobaglia?

**Comment by NoeReboul** [comment]
Hello, the B2C API is not public for the moment. I fully understand your request. We're working on it but I can't give you a schedule.

**Comment by flobz** [comment]
The B2C API is used by android app... 
Therefore it impact the android app.
This problem appeared in March and it isn't fixed even if a lot of people report it to the hotline. please do something

**Comment by NoeReboul** [comment]
I understand your point, but the system works as designed. Location data is not used (and therefore not collected) for the remote control service for electric vehicles. As mentioned, the B2C API is not public and designed for the official application and official services. I know this is not the answer you are looking for. We are working on opening the API.

**Comment by flobz** [comment]
Location is collected and available via the B2B API for third service like Tronity.io. 
So basically to get the position of my own car I should pay for a third service... It make no sense to me. 
I think that PSA should consider to invest in car connectivity because a lot of people regret to didn't buy a tesla...

**Comment by dreimer1986** [comment]
Report is closed, but just my 2 cents about that topic.
It worked fine in the past and still works fine for some cars which did not seem to have got the most recent obviously and utterly broken BTA updates over the air. That is at least what your german support told me after enough nagging. That was MONTHS ago. What's to difficult on reverting to a working state? Or is it no bug at all? Maybe it was planned to happen?
If you did that to sell your B2B API, just tell us. But if you did, then give us a way to get it back! I see a bunch of services in my Android app, all active, but no way to get this back. I bought my e208 after I was shown what features the app has and these features got removed without any warning. I don't wanna throw the law killer argument here, but it's not a nice move to remove features after the car was sold, both in social and law matters.
Right now I am still happy with my car, but this behavior leaves a bad taste which might cause me to move along after my leasing contract ends. Tesla was mentioned already and I have to second that. They provide stuff a PSA customer just can dream of all summed up in a stupid Android app. Features you already had and now start to remove out of nowhere.
Several experts already came to the conclusion that european car manufacturers are left behind already due to their behavior towards modern technology. Times are over where a customer just wants the car to move from a to b. More and more people ask for possibilities to integrate it into their smart home, get flooded with information any time and know where they left it and this is not that easy with any API you provide. Open, outdated and broken v2 or closed and now broken v4.
@flobz gave us a way to at least get what you send to the app. And suddently after it got more mature, you start to not provide relevant information at all anymore. Maybe there is some coincidense, maybe not?

Last words. Maybe we are a minority of ppl who are deep enough in that topic to even know what feature bugged out somewhere in March. Maybe 99% of all customers did not even notice the app fails to provide any location data anymore (same for the API v4 itself), but the number of ppl caring about such features is growing every day. Don't miss the opportunity to give these ppl the data you originally intended to give. *drops the mike*

**Comment by vlycop** [comment]
Personally, I will send back my car for a full computer replacement no mater how many time it will take until this if fixed.
Your app is supposed to show me where I parked my car for exemple l, and because this is broken it never work, my trip ar always 1 day late because of bluetooth sync.
This is a sold feature.
All the software in the car is bad, but this part is easily fixable at least.

Really regretting buying a French car, I should have waited for the German one out 3 month later

**Comment by xammmue** [comment]
I am also annoyed by the software behavior.

While the car hardware is perfectly fine, there are software issues on car, app and API level.

At least the API problems should be easily fixable (also should other things like a charge limit be too), but it seems like PSA / stellantis doesn't really car about customer satisfaction in that regard.
If this does not change I will know what to look for when it comes to buying a new car and it probably won't be one of the Stellantis brands again if the software doesn't improve

**Comment by PatrikNorrgard** [comment]
I just ordered a new car, and literally read the App Terms of service, and they clearly state that the car can be located through the App (Opel Connect), using the vehicle´s GPS. 

I was already let down by PSA once, when you disabled Onstar in my Astra, so I´m feeling really annoyed finding this out.

**Comment by dreimer1986** [comment]
> I understand your point, but the system works as designed. Location data is not used (and therefore not collected) for the remote control service for electric vehicles. As mentioned, the B2C API is not public and designed for the official application and official services. I know this is not the answer you are looking for. We are working on opening the API.

So you claim that it works as designed? Well, what are these settings for then?

https://user-images.githubusercontent.com/15648175/113422594-43341e80-93cd-11eb-849f-d192fb50001d.png
Pic by @Flodu31

What is the explaination for the App Terms of Service explaining it indeed is not working as expected? 

What is the explaination for my sales talk before I decided for buying that car? I was shown the app and all the location features you now claim to not have existed at all.

Questions over questions. Just tell us the truth. We know how a MQTT works, we know that the location data was passed to ['last_position']['geometry']['coordinates'] and now is nulled out. We know that this causes the app to fail doing it's job and we know that it indeed seems to still send that data to your servers. B2B or B2C I don't care, you get the data and I don't care if you collect them. People who don't want that can disable the location data in the car's settings! I want my features back I bought with the car and paid for!

Small sidenote. My boss wanted to replace our old Diesel cars with a bunch (=six cars) of full electric ones. He asked me about my experience with Peugeot/PSA/Stellantis and I told him that it's a nice car, but the app loses features without any warning and support says for months it's being worked on a fix and API maintainers tell us now that this is intended behavior. He laughed and now chose Reanult Zoe cars instead. He is a IT guy, too and he very well understands that this can happen anytime with the other features, too. Losing one feature and then seeing the try to sweep it under the rug is alarming!

Just tell us what's happening now. Do you plan fix it at all? Do you have a priority above 0 for doing so? I don't even ask for a WHEN as long as this WHEN is not in 12 months!

God and heavens, that's the last time I ever get a car by leasing. I am so mad at this company already that I would have brought the car back! You are close to even surpass my anger towards Opel. Killing features after the car was sold and then claiming it's inteded to work that way? Sorry, but... NOPE!

**Comment by jousis9** [comment]
Please reconsider your approach on this matter.
I was also told about this feature by a salesperson and I am very disappointed now.

This is clearly a business decision so please note, our negative experience will influence others*.
A basic (to be polite) cordova app and crippled API will not get you far.


*for example, guess what brand I won't be keen on buying for our other leases. ;)

**Comment by Bonxy** [comment]
I agree with some of the above comments.

Removing features from a product that is part of the 'buying into Vauxhall' process seems ridiculous. Ive only had my car since October and features are already being depreciated?
